# Standardized labels for issues and PRs
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: security
    color: b60205
    description: Security-related
  - name: automerge
    color: 0e8a16
    description: Pull requests eligible for automatic merging
  - name: breaking
    color: 5319e7
    description: Breaking change
  - name: question
    color: d876e3
    description: Further information is requested
